/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ChatConversationSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'fullName',
    'id',
    'messages',
    'profile',
    'title',
    'updatedAt',
    'username',
  ] as const
  $columns = ChatConversationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare messages: string
  @column()
  declare profile: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare username: string
}

export class DirectoryUserSchema extends BaseModel {
  static $columns = [
    'authUserId',
    'createdAt',
    'email',
    'firstName',
    'id',
    'lastName',
    'phoneNumber',
    'role',
    'status',
    'updatedAt',
    'username',
  ] as const
  $columns = DirectoryUserSchema.$columns
  @column()
  declare authUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastName: string
  @column()
  declare phoneNumber: string
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare username: string
}

export class IntegrationSchema extends BaseModel {
  static $columns = ['connected', 'createdAt', 'description', 'name', 'updatedAt'] as const
  $columns = IntegrationSchema.$columns
  @column()
  declare connected: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TaskSchema extends BaseModel {
  static $columns = [
    'assignee',
    'createdAt',
    'description',
    'dueDate',
    'id',
    'label',
    'priority',
    'status',
    'title',
    'updatedAt',
  ] as const
  $columns = TaskSchema.$columns
  @column()
  declare assignee: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column.dateTime()
  declare dueDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string
  @column()
  declare priority: string
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSettingSchema extends BaseModel {
  static $columns = ['createdAt', 'settings', 'updatedAt', 'userId'] as const
  $columns = UserSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare settings: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column({ isPrimary: true })
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = [
    'clerkUserId',
    'createdAt',
    'email',
    'fullName',
    'id',
    'password',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare clerkUserId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
